### ISSUE TITLE
Making gasPrice and gasLimit optional when sending an interaction

### ISSUE THREAD

**Issue by BhimgoudaPatil** [sarvalabs/js-moi-sdk#29]
# Making gasPrice and gasLimit optional when sending an interaction

This proposal is being presented after observing how ethers.js attempts to automatically estimate these two values by making an RPC call to the node for eth_estimateGas and eth_gasPrice.

Instead of users making these RPC calls beforehand, the js-moi-sdk can handle this process automatically by calling our moi.FuelEstimate method and for now our gasPrice is anyways set to 1, thereby enhancing the user experience.

**Comment by sarvalabs-harshrastogi** [comment]
resolved in https://github.com/sarvalabs/js-moi-sdk/pull/36
