### ISSUE TITLE
Remove debug methods from provider

### ISSUE THREAD

**Issue by sarvalabs-prakhar** [sarvalabs/js-moi-sdk#33]
### Description
Remove all the debug methods from `Provider` class

### Steps to Reproduce
NA

### Screenshots
NA

### Expected Behavior
Debug methods should not be accessible from the provider.

### Actual Behavior
Few debug methods are accessible from the provider. 

### Logs
NA

### Proposed Solution
The solution is to remove the methods, and types associated with it and update the docs.

**Comment by sarvalabs-harshrastogi** [comment]
resolved in https://github.com/sarvalabs/js-moi-sdk/pull/36
