### ISSUE TITLE
Getting error when trying to generate keystore from wallet

### ISSUE THREAD

**Issue by sarvalabs-bhavyatomar** [sarvalabs/js-moi-sdk#57]
this is the code I tried (browser environment)

```ts
const wallet = await Wallet.fromMnemonic(
  <mnemonic>,
  "m/44'/6174'/7020'/0/0"
);

console.log(wallet.generateKeystore("Test@123"));
```

This is the error 

![image](https://github.com/sarvalabs/js-moi-sdk/assets/144095991/af3cc505-18f2-46b2-8316-aa39ca54060d)

**Comment by sarvalabs-harshrastogi** [comment]
https://github.com/sarvalabs/js-moi-sdk/pull/65
